const navHandler = require('./nav')
const homeHandler = require('./home')
const createObject = require('./create')
const translationObject = require('./translation')

navHandler.listenForLog()
homeHandler.listenForPostClick()
createObject.listenForSubmission()
translationObject.listenForCommentSub()
translationObject.listenForAnswerSub()
