const navHandler = require('./nav')
const homeHandler = require('./home')
const createObject = require('./create')
const voteHandler = require('./vote')
const translationObject = require('./translation')

navHandler.navListener()
homeHandler.homeListener()
createObject.listenForSubmission()
voteHandler.voteListener()
translationObject.listenForCommentSub()
translationObject.listenForAnswerSub()
